<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8JKSE2M" failures="2" tests="3" name="Test" time="0.064" errors="0" timestamp="2023-05-23T00:26:29 IST">
  <testcase classname="Package.RecentlyPlayedStoreTest" name="testCapacityExceeded" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at Package.RecentlyPlayedStoreTest.testCapacityExceeded(RecentlyPlayedStoreTest.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testCapacityExceeded -->
  <testcase classname="Package.RecentlyPlayedStoreTest" name="testEmptyRecentlyPlayedSongs" time="0.002"/>
  <testcase classname="Package.RecentlyPlayedStoreTest" name="testRecentlyPlayedSongs" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at Package.RecentlyPlayedStoreTest.testRecentlyPlayedSongs(RecentlyPlayedStoreTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testRecentlyPlayedSongs -->
</testsuite> <!-- Test -->
